database_host = "localhost"
database_port = 25432
database_user = "admin"
database_name = "pismo"
database_password = "123456"
ssl_mode = "disable"

queue_login = "dummyUser"
queue_password = "dummyPass"
queue_host = "localhost"
queue_port = "5672"
queue = "events"