
services:
#    event-processor:
#        build:
#            context: .
#        restart: unless-stopped
#        ports:
#            - '${PORT}:${PORT}'
#        environment:
#            - PORT=${PORT}
#
    rabbitmq:
        image: rabbitmq:3.12.4-management
        ports:
            - "15672:15672"
            - "5672:5672"
        networks:
            db_network:
                aliases:
                    - "queue.svc"

        environment:
            RABBITMQ_DEFAULT_USER: dummyUser
            RABBITMQ_DEFAULT_PASS: 'dummyPass'
            RABBITMQ_DEFAULT_VHOST: /

    db:
        image: postgres:13.2
        restart: unless-stopped
        tty: true
        ports:
            - "25432:5432"
        environment:
            POSTGRES_DB: pismo
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 123456
        networks:
            db_network:
                aliases:
                    - "db.svc"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 10s
            timeout: 30s
            retries: 5
            start_period: 30s

    pgadmin:
        image: dpage/pgadmin4
        restart: unless-stopped
        ports:
            - "15432:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: "pismo@example.com"
            PGADMIN_DEFAULT_PASSWORD: "123456"
        networks:
            - db_network
        depends_on:
            db:
                condition: service_healthy

networks:
    db_network:
        driver: bridge
